### ISSUE TITLE
6.3.3 第三段代码未添加高亮

### ISSUE THREAD

**Issue by IndifferentArea** [windsting/a-tour-of-cpp-2nd-cn#1]
![image](https://github.com/windsting/a-tour-of-cpp-2nd-cn/assets/74698401/2f9493cd-4189-4627-a029-dc5161c8eef7)

**Comment by windsting** [comment]
你好，感谢反馈，升级 honkit 版本再 `build` 后，问题得到修复，
请（禁用浏览器缓存后）刷新页面查看修复效果。

**Comment by IndifferentArea** [comment]
已修复，谢谢您的翻译。
