### ISSUE TITLE
是否有翻译本书第三版的计划？

### ISSUE THREAD

**Issue by xflcx1991** [windsting/a-tour-of-cpp-2nd-cn#2]
首先非常感谢作者的努力，在线阅读的体验非常好。

请问是否有翻译第三版的计划？https://stroustrup.com/tour3.html
看到2022年9月即出版

**Comment by windsting** [comment]
第三版的中文版已经有[实体书](https://m.douban.com/book/subject/36596125/)出版，
我现在不像之前那样时间充裕了，
所以，目前没有翻译的计划。

感谢关注。

**Comment by windsting** [comment]
第三版的中文版已经有[实体书](https://m.douban.com/book/subject/36596125/)出版，
我现在不像之前那样时间充裕了，
所以，目前没有翻译的计划。

感谢关注。
